#!/bin/bash
# 	
# kasutaja lisamise skript
# kasutaja nimi tuleb anda skripti parameetrina
# skript peab antud nimega kasutajat lisama süsteemi
# Lisan kasutusjuhendi
if [ $# -ne 1 ]; then
    echo "Kasutusjuhend: $0 kasutajanimi"	
else

  # kasutajanimi on esimene parameeter, seega tuleb kasutada $1 muutujat
  kasutajanimi=$1 
  # kasutame kasutaja lisamise käsk vajalikute võtmetega
  useradd $kasutajanimi -m -s /bin/bash
  #
  if [ $? -eq 0 ]; then
    echo "Kasutaja nimega $kasutajanimi on lisatud süsteemi"
    cat /etc/passwd | grep $kasutajanimi
    ls -la /home/$kasutajanimi
  else
    echo "probleem kasutaja $kasutajanimi lisamisega"
    echo "probleemi kood on $?"
  fi
# skripti õige kasutamise kontrolli lõpp
fi
